name: Build

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:  
      
jobs:
  build:
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [16, 18, 20, 21, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
  report:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Report Status
        if: contains(needs.build.result, 'failure')
        run: exit 1
