name: Build

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:  
      
jobs:
  build:
    continue-on-error: true
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [16, 18, 20, 21, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
